export const dogQuotes = [
    "Pies jest jedynym stworzeniem na Ziemi, które kocha cię bardziej niż siebie samego",
    "Pies uczy cię bezwarunkowej miłości. Jeśli masz takiego, który cię kocha, nie ma wielu rzeczy, które mogłyby być złe w twoim życiu",
    "Psy nie są całym naszym życiem, ale sprawiają, że nasze życie jest całe",
    "Aby właściwie zrozumieć ich znaczenie, każdy powinien mieć psa, który go pokocha, i kota, który go zignoruje",
    "Pies jest jedynym stworzeniem na świecie, które kocha cię bardziej niż siebie",
    "Mój pies myśli, że jestem niesamowity. To dlatego tak bardzo kocham psy",
    "Jeśli nie lubisz psów, prawdopodobnie nie polubisz też ludzi",
    "Pies jest najlepszym przyjacielem człowieka",
    "Pies to nie zabawka, to przyjaciel na całe życie",
    "Dopóki nie pokochałeś psa, część twojej duszy pozostaje uśpiona",
    "Pies ma tyle wdzięczności, że aż wstydzisz się, że jesteś człowiekiem",
    "Psy nie są naszym całym życiem, ale czynią je kompletnymi",
    "Pies jest jedynym stworzeniem, które kocha cię bezwarunkowo",
    "Najlepszy przyjaciel to ten, który cię kocha, nawet gdy ty sam siebie nie lubisz",
    "Pies to nie tylko zwierzę, to członek rodziny",
    "Pies to najlepszy terapeuta, jakiego możesz mieć",
    "Pies to lustro, w którym możesz zobaczyć swoje najlepsze cechy",
    "Pies to anioł na czterech łapach",
    "Pies to dar od Boga, który uczy nas miłości i lojalności",
];
